// Milk Depot Recipe Data
// NUTRITION IS ESTIMATED BASED ON WHOLE INGREDIENTS - SEE DISCLAIMER

const recipes = [
    // --- ALMOND ---
    { id: "almond001", name: "Classic Creamy Almond", ingredients: ["1 cup Raw Almonds (soaking optional)"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Vanilla Extract", "Pinch Pink Himalayan Salt"], description: "The timeless favorite! This classic almond milk is smooth, subtly sweet, and incredibly versatile. Soaking the almonds beforehand can yield an even creamier result.\n\nPerfect for pouring over cereal, blending into smoothies, adding to your morning coffee, or using in baking recipes. It's a fantastic dairy-free staple.", nutrition: { calories: 65, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 4, fiber_g: 1, sugars_g: 3, protein_g: 2, calcium_mg: 70, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 60 } },
    { id: "almond002", name: "Vanilla Bean Dream Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["1 tsp Vanilla Bean Paste (or 1 scraped bean)", "2 tsp Monk Fruit Sweetener", "Pinch Sea Salt"], description: "Elevate your almond milk with the intense, aromatic flavor of real vanilla bean. Uses monk fruit for sweetness without added sugar.\n\nWonderful in lattes, poured over fresh berries, or used as a base for chia seed pudding. Adds a touch of luxury.", nutrition: { calories: 45, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 1, fiber_g: 1, sugars_g: 0, protein_g: 2, calcium_mg: 60, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 60 } },
    { id: "almond003", name: "Honey Kissed Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["1.5 tbsp Honey", "Pinch Salt"], description: "A gentle sweetness from pure honey makes this almond milk naturally satisfying. It has a warm, comforting flavor.\n\nTry it warmed with a cinnamon stick for a cozy evening drink, or use it in oatmeal. Great for children.", nutrition: { calories: 75, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 6, fiber_g: 1, sugars_g: 5, protein_g: 2, calcium_mg: 60, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 65 } },
    { id: "almond004", name: "Chocolate Delight Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["2 tbsp Cocoa Powder (unsweetened)", "1.5 tbsp Maple Syrup", "1/4 tsp Vanilla Extract", "Pinch Salt"], description: "A healthy indulgence! Rich cocoa powder transforms simple almond milk into a delicious chocolate treat. Perfectly balanced.\n\nAmazing on its own, blended with a banana for a smoothie, or gently heated for hot cocoa. A hit with everyone!", nutrition: { calories: 85, fat_g: 5.5, saturated_fat_g: 0.6, carbs_g: 7, fiber_g: 2, sugars_g: 3.5, protein_g: 2.5, calcium_mg: 65, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 120 } },
    { id: "almond005", name: "Spiced Chai Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["1 tbsp Maple Syrup", "1 tsp Chai Spice Blend", "Pinch Black Pepper", "Pinch Salt"], description: "Warm and inviting chai spices infuse this almond milk with exotic flavor. Perfect balance of spice and sweetness.\n\nExcellent base for homemade chai lattes, delicious warmed up, or adds a unique twist to oatmeal.", nutrition: { calories: 65, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 4, fiber_g: 1, sugars_g: 3, protein_g: 2, calcium_mg: 70, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 70 } },
    { id: "almond006", name: "Lavender Honey Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["1 tsp Dried Culinary Lavender", "1.5 tbsp Honey", "Pinch Salt"], description: "A calming and fragrant milk. Delicate floral notes of lavender pair beautifully with honey. Ensure lavender is culinary grade!\n\nLovely served chilled or slightly warmed before bed. Can also add unique flavor to shortbread or scones.", nutrition: { calories: 75, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 6, fiber_g: 1, sugars_g: 5, protein_g: 2, calcium_mg: 60, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 65 } },
    { id: "almond007", name: "Maple Ginger Almond Zing", ingredients: ["1 cup Raw Almonds"], flavorings: ["1.5 tbsp Maple Syrup", "1/2 tsp Ground Ginger", "Pinch Salt"], description: "A simple but invigorating blend. The warmth of ginger provides a pleasant kick against the sweet maple and creamy almond base.\n\nNice addition to tea, great for soothing a sore throat when warmed, or adds spice to smoothies.", nutrition: { calories: 70, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 5, fiber_g: 1, sugars_g: 4, protein_g: 2, calcium_mg: 70, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 65 } },
    // --- CASHEW ---
    { id: "cashew001", name: "Silky Smooth Cashew", ingredients: ["1 cup Raw Cashews (soaking optional)"], flavorings: ["1 tbsp Agave Nectar", "1/2 tsp Vanilla Extract", "Pinch Salt"], description: "Incredibly creamy, naturally rich texture. Soaking results in silky smooth milk. Agave provides clean sweetness.\n\nExcellent for creamy soups, sauces, vegan mac 'n' cheese bases, or enjoyed by the glass. Neutral flavor.", nutrition: { calories: 80, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 5, fiber_g: 0.5, sugars_g: 4, protein_g: 2.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 90 } },
    { id: "cashew002", name: "Maple Pecan Cashew Kiss", ingredients: ["3/4 cup Raw Cashews", "1/4 cup Pecans"], flavorings: ["1.5 tbsp Maple Syrup", "1/4 tsp Maple Extract (optional)", "Pinch Salt"], description: "A decadent blend of creamy cashews and buttery pecans, sweetened with maple syrup. Comforting and slightly nutty.\n\nPerfect for fall/winter beverages, coffee, or pancake batter. Feels like a special treat!", nutrition: { calories: 110, fat_g: 9, saturated_fat_g: 1, carbs_g: 6, fiber_g: 1, sugars_g: 4, protein_g: 2.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 95 } },
    { id: "cashew003", name: "Strawberry Cashew Swirl", ingredients: ["1 cup Raw Cashews"], flavorings: ["1/3 cup Fresh or Frozen Strawberries", "1 tbsp Honey", "Pinch Salt"], description: "Creamy cashew milk meets bright, sweet strawberries. Naturally pink and delightful, especially loved by kids.\n\nPerfect for drinking plain, smoothies, or over fruit salad. A taste of springtime!", nutrition: { calories: 90, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 7, fiber_g: 1, sugars_g: 5.5, protein_g: 2.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.9, potassium_mg: 120 } },
    { id: "cashew004", name: "Cardamom Rose Cashew", ingredients: ["1 cup Raw Cashews"], flavorings: ["1 tbsp Agave Nectar", "1/2 tsp Ground Cardamom", "1/4 tsp Rose Water (food grade!)"], description: "An exotic and aromatic treat. Creamy cashews infused with the floral notes of rose and the warm spice of cardamom. Feels very sophisticated.\n\nPerfect for unique lattes, flavoring Middle Eastern or Indian-inspired desserts, or simply sipping for a moment of indulgence.", nutrition: { calories: 85, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 6, fiber_g: 0.5, sugars_g: 4.5, protein_g: 2.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 100 } },
    // --- OAT ---
    { id: "oat001", name: "Everyday Oat Milk", ingredients: ["1 cup Rolled Oats (GF if needed)"], flavorings: ["1 tbsp Maple Syrup", "Pinch Salt"], description: "Your go-to, budget-friendly plant milk! Naturally slightly sweet and creamy. Use rolled oats for best texture.\n\nFantastic in coffee (it froths!), granola, baking, or drinking. Versatile and sustainable.", nutrition: { calories: 60, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 11, fiber_g: 1, sugars_g: 4, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 50 } },
    { id: "oat002", name: "Cinnamon Swirl Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1 tsp Ground Cinnamon", "1 tbsp Coconut Sugar", "1/4 tsp Vanilla Extract", "Pinch Salt"], description: "Warm cinnamon spice elevates simple oat milk. Coconut sugar adds caramel sweetness. Comfort in a glass!\n\nDelicious warmed up, splashed into chai tea, or used as a base for oatmeal. Cozy and inviting.", nutrition: { calories: 75, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 15, fiber_g: 1.5, sugars_g: 5, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 60 } },
    { id: "oat003", name: "Blueberry Burst Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1/4 cup Fresh or Frozen Blueberries", "1 tbsp Maple Syrup", "Pinch Salt"], description: "A fruity twist! Blueberries give a beautiful color and fresh, tangy flavor. Perfect taste of summer.\n\nGreat for smoothies, cereal, or as a refreshing drink. Kids often love the fun color!", nutrition: { calories: 70, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 14, fiber_g: 1.5, sugars_g: 6, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 60 } },
    { id: "oat004", name: "Golden Turmeric Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1 tsp Ground Turmeric", "1/4 tsp Ground Ginger", "Pinch Black Pepper", "1 tbsp Maple Syrup", "Pinch Salt"], description: "A vibrant 'Golden Milk' base. Earthy turmeric and spicy ginger create a warming, anti-inflammatory blend.\n\nTraditionally enjoyed warm. Add cinnamon or cardamom too. Great for wellness.", nutrition: { calories: 65, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 12, fiber_g: 1.5, sugars_g: 4, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 70 } },
    { id: "oat005", name: "Peachy Keen Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1/3 cup Peach Slices (fresh or frozen)", "1 tsp Honey", "Pinch Ginger (optional)"], description: "A summery delight! Sweet peaches blend beautifully with creamy oat milk for a refreshing treat. A hint of ginger adds a nice zing.\n\nPerfect chilled on a hot day, blended into a breakfast smoothie, or used to make peach-flavored overnight oats.", nutrition: { calories: 65, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 13, fiber_g: 1.5, sugars_g: 6, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 75 } },
    // --- COCONUT ---
    { id: "coconut001", name: "Tropical Breeze Coconut", ingredients: ["1 cup Unsweetened Shredded Coconut"], flavorings: ["1 tbsp Agave Nectar", "1/4 tsp Vanilla Extract (optional)"], description: "Pure tropical delight! Light yet distinctly coconutty. Adjust sweetness.\n\nIdeal for smoothies, curries, piña coladas, or adding flair to coffee/desserts. Brings the beach to you!", nutrition: { calories: 70, fat_g: 6.5, saturated_fat_g: 6, carbs_g: 3, fiber_g: 1, sugars_g: 2, protein_g: 0.5, calcium_mg: 5, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 50 } },
    { id: "coconut002", name: "Creamy Dream Coconut", ingredients: ["1 cup Coconut Cream (unsweetened, from can)"], flavorings: ["1 tsp Maple Syrup (optional)", "Pinch Salt"], description: "Extra richness! Uses coconut cream for luxuriously thick milk. A little goes a long way.\n\nPerfect coffee creamer, whipped topping, curry thickener, or vegan ice cream base. High fat/calories.", nutrition: { calories: 150, fat_g: 15, saturated_fat_g: 13, carbs_g: 2, fiber_g: 0.5, sugars_g: 1, protein_g: 1.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 1, potassium_mg: 150 } },
    { id: "coconut003", name: "Lime & Coconut Refresher", ingredients: ["1 cup Unsweetened Shredded Coconut"], flavorings: ["1 tbsp Lime Juice", "1 tsp Lime Zest", "1.5 tbsp Agave Nectar", "Pinch Salt"], description: "Zesty and refreshing! Bright lime tang cuts through coconut richness. Tastes like a vacation!\n\nFantastic in smoothies, mocktails, or marinades. Perfect for summer.", nutrition: { calories: 80, fat_g: 6.5, saturated_fat_g: 6, carbs_g: 5, fiber_g: 1, sugars_g: 4, protein_g: 0.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 60 } },
    // --- HEMP ---
    { id: "hemp001", name: "Powerhouse Hemp Milk", ingredients: ["1/2 cup Hulled Hemp Seeds (Hemp Hearts)"], flavorings: ["1 tbsp Maple Syrup", "1/4 tsp Vanilla Extract", "Pinch Salt"], description: "Nutrient-dense and delicious! Creamy milk with nutty, earthy flavor. Great source of protein & healthy fats.\n\nExcellent post-workout, in cereals, or savory dishes. Nutritional powerhouse!", nutrition: { calories: 90, fat_g: 8, saturated_fat_g: 0.8, carbs_g: 4, fiber_g: 0.5, sugars_g: 3, protein_g: 5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 1.5, potassium_mg: 180 } },
    { id: "hemp002", name: "Go Green Hemp", ingredients: ["1/2 cup Hulled Hemp Seeds"], flavorings: ["1 tsp Matcha Powder", "1 tbsp Honey", "Pinch Salt"], description: "Energizing, vibrant green milk! Earthy matcha pairs well with nutty hemp, sweetened with honey.\n\nPerfect morning boost, green smoothie base, or unique latte. Packed with antioxidants.", nutrition: { calories: 100, fat_g: 8, saturated_fat_g: 0.8, carbs_g: 6, fiber_g: 1, sugars_g: 4.5, protein_g: 5.5, calcium_mg: 25, vitamin_d_iu: 0, iron_mg: 1.7, potassium_mg: 190 } },
    { id: "hemp003", name: "Banana Bread Hemp", ingredients: ["1/2 cup Hulled Hemp Seeds"], flavorings: ["1/4 Ripe Banana (mashed)", "1/2 tsp Cinnamon", "1/4 tsp Nutmeg", "1 tbsp Maple Syrup", "Pinch Salt"], description: "Flavors of banana bread in nutritious milk! Banana adds sweetness and creaminess, paired with warm spices.\n\nIncredible in smoothies, oatmeal, or sipped alone. Comforting and satisfying.", nutrition: { calories: 110, fat_g: 8, saturated_fat_g: 0.9, carbs_g: 8, fiber_g: 1, sugars_g: 5, protein_g: 5, calcium_mg: 25, vitamin_d_iu: 0, iron_mg: 1.6, potassium_mg: 230 } },
    // --- SEED BLENDS ---
    { id: "seed001", name: "Triple Seed Sunshine", ingredients: ["1/3 cup Pumpkin Seeds (Pepitas)", "1/3 cup Sunflower Seeds", "1/3 cup Hemp Hearts"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Vanilla Extract", "Pinch Salt"], description: "Wonderfully nutty and nutrient-packed milk combining three powerhouse seeds. Balanced flavor, good source of minerals.\n\nGreat nut-free alternative. Use in smoothies, granola, or savory recipes.", nutrition: { calories: 110, fat_g: 9, saturated_fat_g: 1, carbs_g: 5, fiber_g: 1, sugars_g: 3, protein_g: 4, calcium_mg: 25, vitamin_d_iu: 0, iron_mg: 1.5, potassium_mg: 150 } },
    { id: "seed002", name: "Pumpkin Spice Seed Delight", ingredients: ["1/2 cup Pumpkin Seeds", "1/4 cup Sunflower Seeds"], flavorings: ["1 tsp Pumpkin Pie Spice", "1.5 tbsp Maple Syrup", "1/4 tsp Vanilla Extract"], description: "Embrace autumn! Creamy pumpkin/sunflower seed milk infused with warming pumpkin pie spice. Cozy treat.\n\nPerfect for fall lattes, oatmeal, or seasonal baking. Makes kitchen smell amazing!", nutrition: { calories: 100, fat_g: 8, saturated_fat_g: 1, carbs_g: 6, fiber_g: 1, sugars_g: 4, protein_g: 3.5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 1.6, potassium_mg: 140 } },
    { id: "seed003", name: "Chia Charge Seed Milk", ingredients: ["1/2 cup Chia Seeds", "1/2 cup Sunflower Seeds"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Cinnamon"], description: "Thick and nutritious! Chia seeds create a gel-like consistency when blended, making this milk naturally thicker. Combined with sunflower seeds for flavor and fats.\n\nNeeds a good shake before serving. Great for making puddings or adding extra fiber and thickness to smoothies.", nutrition: { calories: 90, fat_g: 6.5, saturated_fat_g: 0.7, carbs_g: 8, fiber_g: 4, sugars_g: 3, protein_g: 3.5, calcium_mg: 100, vitamin_d_iu: 0, iron_mg: 1.5, potassium_mg: 100 } },
    // --- NUT BLENDS ---
    { id: "nutblend001", name: "Almond Cashew Dream", ingredients: ["1/2 cup Raw Almonds", "1/2 cup Raw Cashews"], flavorings: ["1 tbsp Maple Syrup", "1/4 tsp Vanilla Extract", "Pinch Salt"], description: "Best of both worlds! Classic almond taste with incredible cashew creaminess. Dreamy texture and flavor.\n\nFantastic all-around milk. Use anywhere for an upgrade in richness. Superb in coffee.", nutrition: { calories: 75, fat_g: 6, saturated_fat_g: 0.8, carbs_g: 4.5, fiber_g: 1, sugars_g: 3, protein_g: 2.5, calcium_mg: 40, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 75 } },
    { id: "nutblend002", name: "Macadamia Hazelnut Luxe", ingredients: ["1/2 cup Raw Macadamia Nuts", "1/2 cup Raw Hazelnuts"], flavorings: ["1 tbsp Honey", "1/4 tsp Almond Extract (optional)", "Pinch Salt"], description: "Pure indulgence! Buttery macadamias meet aromatic hazelnuts for a rich, luxurious milk. Naturally slightly sweet.\n\nAmazing coffee creamer, warmed drink, or elevates desserts. High-fat treat!", nutrition: { calories: 140, fat_g: 14, saturated_fat_g: 2, carbs_g: 4, fiber_g: 1.5, sugars_g: 2.5, protein_g: 2, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 0.7, potassium_mg: 100 } },
    { id: "nutblend003", name: "Walnut Wonder", ingredients: ["1 cup Raw Walnuts (lightly toasted optional)"], flavorings: ["1 tbsp Maple Syrup", "1/4 tsp Cinnamon", "Pinch Salt"], description: "Distinctive, slightly earthy flavor of walnuts shines through. Rich in Omega-3s. Cinnamon adds warmth. Toasting optional.\n\nGood in smoothies, oatmeal, or savory applications where its unique flavor complements.", nutrition: { calories: 110, fat_g: 10, saturated_fat_g: 1, carbs_g: 5, fiber_g: 1, sugars_g: 3.5, protein_g: 2.5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 70 } },
    { id: "nutblend004", name: "ABC Milk (Almond, Brazil, Cashew)", ingredients: ["1/2 cup Raw Almonds", "1/4 cup Raw Brazil Nuts", "1/4 cup Raw Cashews"], flavorings: ["1 tbsp Agave Nectar", "1/4 tsp Vanilla", "Pinch Salt"], description: "A powerhouse blend known for its nutrient density, especially selenium from Brazil nuts! Combines creaminess with a range of nutty flavors.\n\nExcellent nutritional boost for smoothies or enjoyed daily. Use Brazil nuts sparingly.", nutrition: { calories: 100, fat_g: 9, saturated_fat_g: 1.5, carbs_g: 4, fiber_g: 1, sugars_g: 3, protein_g: 3, calcium_mg: 50, vitamin_d_iu: 0, iron_mg: 0.7, potassium_mg: 110 } },
    // --- GRAIN BLENDS ---
    { id: "grain001", name: "Oat & Rice Serenity", ingredients: ["1/2 cup Rolled Oats", "1/2 cup Cooked Brown Rice"], flavorings: ["1 tbsp Agave Nectar", "1/4 tsp Vanilla Extract", "Pinch Salt"], description: "Mild, smooth, easily digestible milk blending oat creaminess with gentle rice taste. Great for sensitive systems.\n\nNeutral flavor, perfect for everyday use in cereal, smoothies, or cooking.", nutrition: { calories: 55, fat_g: 0.8, saturated_fat_g: 0.1, carbs_g: 11, fiber_g: 1, sugars_g: 3.5, protein_g: 1.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 40 } },
    // --- MIXED BLENDS ---
    { id: "mixed001", name: "Sunrise Blend (Oat, Almond, Sunflower)", ingredients: ["1/3 cup Rolled Oats", "1/3 cup Raw Almonds", "1/3 cup Sunflower Seeds"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Vanilla Extract", "Pinch Salt"], description: "Bright start! Creaminess from oats, nuttiness from almonds, mineral boost from sunflower seeds. Well-rounded.\n\nExcellent all-purpose milk. Great over granola, in smoothies, or chilled.", nutrition: { calories: 80, fat_g: 5, saturated_fat_g: 0.5, carbs_g: 7, fiber_g: 1.5, sugars_g: 3, protein_g: 3, calcium_mg: 30, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 90 } },
    { id: "mixed002", name: "Midnight Velvet (Cashew, Hemp, Cocoa)", ingredients: ["1/2 cup Raw Cashews", "1/4 cup Hemp Hearts"], flavorings: ["2 tbsp Cocoa Powder", "1.5 tbsp Maple Syrup", "1/4 tsp Vanilla", "Pinch Salt"], description: "Rich, dark, velvety smooth. Creamy cashews & protein-packed hemp get a decadent chocolate infusion.\n\nPerfect standalone drink, hot or cold. Makes amazing chia pudding or mocha base.", nutrition: { calories: 115, fat_g: 8.5, saturated_fat_g: 1.5, carbs_g: 8, fiber_g: 2, sugars_g: 4, protein_g: 4.5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 1.5, potassium_mg: 180 } },
    { id: "mixed003", name: "Tropical Power Mix (Coconut, Hemp, Pineapple)", ingredients: ["1/2 cup Unsweetened Shredded Coconut", "1/4 cup Hemp Hearts"], flavorings: ["1/4 cup Pineapple Chunks (fresh or frozen)", "1 tsp Agave Nectar (optional)", "Pinch Salt"], description: "A taste of the tropics with a protein punch! Creamy coconut and hemp meet tangy pineapple.\n\nFantastic smoothie base or enjoyed chilled as a refreshing, energizing drink.", nutrition: { calories: 100, fat_g: 8.5, saturated_fat_g: 6.5, carbs_g: 5, fiber_g: 1, sugars_g: 3, protein_g: 3, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 1, potassium_mg: 120 } },
    // --- OTHER BASES ---
    { id: "pistachio001", name: "Emerald Pistachio Milk", ingredients: ["1 cup Raw Pistachios (shelled)"], flavorings: ["1 tbsp Honey", "1/4 tsp Cardamom (optional)", "Pinch Salt"], description: "Unique and elegant milk with beautiful light green hue and distinct pistachio flavor. Cardamom adds lovely aroma.\n\nWonderful for special occasions, desserts like panna cotta, or flavoring baked goods. Gourmet treat.", nutrition: { calories: 95, fat_g: 7.5, saturated_fat_g: 0.9, carbs_g: 6, fiber_g: 1.5, sugars_g: 4, protein_g: 3, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 150 } },
    { id: "soy001", name: "Classic Homemade Soy", ingredients: ["1/2 cup Dried Soybeans (soaked overnight, skins removed optional)"], flavorings: ["1 tbsp Maple Syrup (optional)", "Pinch Salt"], description: "Make your own soy milk! Soaking/deskinning results in cleaner flavor. Complete plant protein.\n\nVersatile for drinking, cooking, baking, making tofu. Ensure beans are well-cooked if machine doesn't heat.", nutrition: { calories: 60, fat_g: 3, saturated_fat_g: 0.4, carbs_g: 4, fiber_g: 1, sugars_g: 1, protein_g: 5, calcium_mg: 40, vitamin_d_iu: 0, iron_mg: 1, potassium_mg: 180 } },
    { id: "rice001", name: "Gentle Rice Milk", ingredients: ["1 cup Cooked Brown Rice (or white)"], flavorings: ["1 tbsp Agave Nectar", "1/2 tsp Vanilla Extract", "Pinch Salt"], description: "Very light, naturally sweet, easily digestible. Often most hypoallergenic.\n\nGood choice for allergies/sensitivities. Thin texture great for drinking/light smoothies, less for creamy coffee.", nutrition: { calories: 70, fat_g: 1, saturated_fat_g: 0.1, carbs_g: 14, fiber_g: 0.5, sugars_g: 6, protein_g: 0.5, calcium_mg: 5, vitamin_d_iu: 0, iron_mg: 0.2, potassium_mg: 20 } },
    { id: "walnut001", name: "Toasted Walnut Wonder", ingredients: ["1 cup Walnuts (lightly toasted optional)"], flavorings: ["1 tbsp Maple Syrup", "1/4 tsp Cinnamon", "Pinch Salt"], description: "Rich and robust! Walnuts provide a distinct, slightly earthy flavor and are packed with Omega-3s. Toasting brings out deeper notes.\n\nGreat in coffee, smoothies, or savory applications like creamy pasta sauces. Its strong flavor stands out.", nutrition: { calories: 110, fat_g: 10, saturated_fat_g: 1, carbs_g: 5, fiber_g: 1, sugars_g: 3.5, protein_g: 2.5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 70 } }
    // Add more recipes here... Remember the comma after the closing } brace, except for the VERY LAST recipe.
]; // End of the recipes array
