// Milk Depot Recipe Data
// NUTRITION IS ESTIMATED BASED ON WHOLE INGREDIENTS - SEE DISCLAIMER

const recipes = [
    // --- ORIGINAL RECIPES (First ~30) ---
    { id: "almond001", name: "Classic Creamy Almond", ingredients: ["1 cup Raw Almonds (soaking optional)"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Vanilla Extract", "Pinch Pink Himalayan Salt"], description: "The timeless favorite! Smooth, subtly sweet, versatile. Soaking optional for extra creaminess.\n\nPerfect for cereal, smoothies, coffee, baking. A fantastic dairy-free staple.", nutrition: { calories: 65, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 4, fiber_g: 1, sugars_g: 3, protein_g: 2, calcium_mg: 70, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 60 } },
    { id: "almond002", name: "Vanilla Bean Dream Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["1 tsp Vanilla Bean Paste (or 1 scraped bean)", "2 tsp Monk Fruit Sweetener", "Pinch Sea Salt"], description: "Elevated almond milk with intense vanilla bean flavor, sweetened with monk fruit.\n\nWonderful in lattes, over berries, or in chia pudding. Adds a touch of luxury.", nutrition: { calories: 45, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 1, fiber_g: 1, sugars_g: 0, protein_g: 2, calcium_mg: 60, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 60 } },
    { id: "almond003", name: "Honey Kissed Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["1.5 tbsp Honey", "Pinch Salt"], description: "Gentle sweetness from pure honey. Warm, comforting flavor.\n\nTry warmed with cinnamon, or in oatmeal. Great for children.", nutrition: { calories: 75, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 6, fiber_g: 1, sugars_g: 5, protein_g: 2, calcium_mg: 60, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 65 } },
    { id: "almond004", name: "Chocolate Delight Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["2 tbsp Cocoa Powder (unsweetened)", "1.5 tbsp Maple Syrup", "1/4 tsp Vanilla Extract", "Pinch Salt"], description: "Healthy indulgence! Rich cocoa makes a delicious chocolate treat, perfectly balanced.\n\nAmazing alone, in smoothies, or as hot cocoa. A hit with everyone!", nutrition: { calories: 85, fat_g: 5.5, saturated_fat_g: 0.6, carbs_g: 7, fiber_g: 2, sugars_g: 3.5, protein_g: 2.5, calcium_mg: 65, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 120 } },
    { id: "almond005", name: "Spiced Chai Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["1 tbsp Maple Syrup", "1 tsp Chai Spice Blend", "Pinch Black Pepper", "Pinch Salt"], description: "Warm, inviting chai spices infuse exotic flavor. Perfect balance.\n\nExcellent base for chai lattes, delicious warmed, unique twist for oatmeal.", nutrition: { calories: 65, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 4, fiber_g: 1, sugars_g: 3, protein_g: 2, calcium_mg: 70, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 70 } },
    { id: "almond006", name: "Lavender Honey Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["1 tsp Dried Culinary Lavender", "1.5 tbsp Honey", "Pinch Salt"], description: "Calming and fragrant. Delicate lavender pairs with honey. Ensure culinary grade lavender!\n\nLovely chilled or warm. Unique flavor for shortbread.", nutrition: { calories: 75, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 6, fiber_g: 1, sugars_g: 5, protein_g: 2, calcium_mg: 60, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 65 } },
    { id: "almond007", name: "Maple Ginger Almond Zing", ingredients: ["1 cup Raw Almonds"], flavorings: ["1.5 tbsp Maple Syrup", "1/2 tsp Ground Ginger", "Pinch Salt"], description: "Simple but invigorating. Warm ginger kick against sweet maple and creamy almond.\n\nNice in tea, soothing when warmed, adds spice to smoothies.", nutrition: { calories: 70, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 5, fiber_g: 1, sugars_g: 4, protein_g: 2, calcium_mg: 70, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 65 } },
    { id: "cashew001", name: "Silky Smooth Cashew", ingredients: ["1 cup Raw Cashews (soaking optional)"], flavorings: ["1 tbsp Agave Nectar", "1/2 tsp Vanilla Extract", "Pinch Salt"], description: "Incredibly creamy, naturally rich texture. Agave provides clean sweetness.\n\nExcellent for creamy soups, sauces, vegan mac 'n' cheese, or enjoyed plain. Neutral flavor.", nutrition: { calories: 80, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 5, fiber_g: 0.5, sugars_g: 4, protein_g: 2.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 90 } },
    { id: "cashew002", name: "Maple Pecan Cashew Kiss", ingredients: ["3/4 cup Raw Cashews", "1/4 cup Pecans"], flavorings: ["1.5 tbsp Maple Syrup", "1/4 tsp Maple Extract (optional)", "Pinch Salt"], description: "Decadent blend of creamy cashews and buttery pecans, sweetened with maple.\n\nPerfect for fall/winter beverages, coffee, pancake batter. A special treat!", nutrition: { calories: 110, fat_g: 9, saturated_fat_g: 1, carbs_g: 6, fiber_g: 1, sugars_g: 4, protein_g: 2.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 95 } },
    { id: "cashew003", name: "Strawberry Cashew Swirl", ingredients: ["1 cup Raw Cashews"], flavorings: ["1/3 cup Fresh or Frozen Strawberries", "1 tbsp Honey", "Pinch Salt"], description: "Creamy cashew milk meets bright strawberries. Naturally pink, loved by kids.\n\nPerfect plain, in smoothies, or over fruit. Taste of springtime!", nutrition: { calories: 90, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 7, fiber_g: 1, sugars_g: 5.5, protein_g: 2.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.9, potassium_mg: 120 } },
    { id: "cashew004", name: "Cardamom Rose Cashew", ingredients: ["1 cup Raw Cashews"], flavorings: ["1 tbsp Agave Nectar", "1/2 tsp Ground Cardamom", "1/4 tsp Rose Water (food grade!)"], description: "Exotic and aromatic. Creamy cashews with floral rose and warm cardamom.\n\nPerfect for unique lattes, flavoring desserts, or sipping. Sophisticated.", nutrition: { calories: 85, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 6, fiber_g: 0.5, sugars_g: 4.5, protein_g: 2.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 100 } },
    { id: "oat001", name: "Everyday Oat Milk", ingredients: ["1 cup Rolled Oats (GF if needed)"], flavorings: ["1 tbsp Maple Syrup", "Pinch Salt"], description: "Go-to, budget-friendly milk! Naturally slightly sweet and creamy.\n\nFantastic in coffee, granola, baking, or drinking. Versatile and sustainable.", nutrition: { calories: 60, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 11, fiber_g: 1, sugars_g: 4, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 50 } },
    { id: "oat002", name: "Cinnamon Swirl Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1 tsp Ground Cinnamon", "1 tbsp Coconut Sugar", "1/4 tsp Vanilla Extract", "Pinch Salt"], description: "Warm cinnamon elevates simple oat milk. Coconut sugar adds caramel sweetness.\n\nDelicious warmed, in chai tea, or oatmeal base. Cozy.", nutrition: { calories: 75, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 15, fiber_g: 1.5, sugars_g: 5, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 60 } },
    { id: "oat003", name: "Blueberry Burst Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1/4 cup Fresh or Frozen Blueberries", "1 tbsp Maple Syrup", "Pinch Salt"], description: "Fruity twist! Blueberries give color and tangy flavor. Taste of summer.\n\nGreat for smoothies, cereal, or refreshing drink. Kids love the color!", nutrition: { calories: 70, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 14, fiber_g: 1.5, sugars_g: 6, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 60 } },
    { id: "oat004", name: "Golden Turmeric Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1 tsp Ground Turmeric", "1/4 tsp Ground Ginger", "Pinch Black Pepper", "1 tbsp Maple Syrup", "Pinch Salt"], description: "Vibrant 'Golden Milk' base. Earthy turmeric and spicy ginger in creamy oats.\n\nTraditionally enjoyed warm. Great for wellness.", nutrition: { calories: 65, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 12, fiber_g: 1.5, sugars_g: 4, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 70 } },
    { id: "oat005", name: "Peachy Keen Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1/3 cup Peach Slices (fresh or frozen)", "1 tsp Honey", "Pinch Ginger (optional)"], description: "Summery delight! Sweet peaches blend with creamy oats. Ginger adds zing.\n\nPerfect chilled, in smoothies, or peach overnight oats.", nutrition: { calories: 65, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 13, fiber_g: 1.5, sugars_g: 6, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 75 } },
    { id: "coconut001", name: "Tropical Breeze Coconut", ingredients: ["1 cup Unsweetened Shredded Coconut"], flavorings: ["1 tbsp Agave Nectar", "1/4 tsp Vanilla Extract (optional)"], description: "Pure tropical delight! Light yet distinctly coconutty.\n\nIdeal for smoothies, curries, piña coladas, coffee. Brings the beach to you!", nutrition: { calories: 70, fat_g: 6.5, saturated_fat_g: 6, carbs_g: 3, fiber_g: 1, sugars_g: 2, protein_g: 0.5, calcium_mg: 5, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 50 } },
    { id: "coconut002", name: "Creamy Dream Coconut", ingredients: ["1 cup Coconut Cream (unsweetened, from can)"], flavorings: ["1 tsp Maple Syrup (optional)", "Pinch Salt"], description: "Extra richness! Uses coconut cream for thick milk.\n\nPerfect coffee creamer, whipped topping, curry thickener, vegan ice cream base. High fat/calories.", nutrition: { calories: 150, fat_g: 15, saturated_fat_g: 13, carbs_g: 2, fiber_g: 0.5, sugars_g: 1, protein_g: 1.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 1, potassium_mg: 150 } },
    { id: "coconut003", name: "Lime & Coconut Refresher", ingredients: ["1 cup Unsweetened Shredded Coconut"], flavorings: ["1 tbsp Lime Juice", "1 tsp Lime Zest", "1.5 tbsp Agave Nectar", "Pinch Salt"], description: "Zesty and refreshing! Bright lime tang cuts through coconut richness.\n\nFantastic in smoothies, mocktails, marinades. Perfect for summer.", nutrition: { calories: 80, fat_g: 6.5, saturated_fat_g: 6, carbs_g: 5, fiber_g: 1, sugars_g: 4, protein_g: 0.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 60 } },
    { id: "hemp001", name: "Powerhouse Hemp Milk", ingredients: ["1/2 cup Hulled Hemp Seeds (Hemp Hearts)"], flavorings: ["1 tbsp Maple Syrup", "1/4 tsp Vanilla Extract", "Pinch Salt"], description: "Nutrient-dense! Creamy milk with nutty, earthy flavor. Great source of protein & healthy fats.\n\nExcellent post-workout, in cereals, savory dishes. Nutritional powerhouse!", nutrition: { calories: 90, fat_g: 8, saturated_fat_g: 0.8, carbs_g: 4, fiber_g: 0.5, sugars_g: 3, protein_g: 5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 1.5, potassium_mg: 180 } },
    { id: "hemp002", name: "Go Green Hemp", ingredients: ["1/2 cup Hulled Hemp Seeds"], flavorings: ["1 tsp Matcha Powder", "1 tbsp Honey", "Pinch Salt"], description: "Energizing green milk! Earthy matcha pairs with nutty hemp, sweetened with honey.\n\nPerfect morning boost, green smoothie base, unique latte. Antioxidant-packed.", nutrition: { calories: 100, fat_g: 8, saturated_fat_g: 0.8, carbs_g: 6, fiber_g: 1, sugars_g: 4.5, protein_g: 5.5, calcium_mg: 25, vitamin_d_iu: 0, iron_mg: 1.7, potassium_mg: 190 } },
    { id: "hemp003", name: "Banana Bread Hemp", ingredients: ["1/2 cup Hulled Hemp Seeds"], flavorings: ["1/4 Ripe Banana (mashed)", "1/2 tsp Cinnamon", "1/4 tsp Nutmeg", "1 tbsp Maple Syrup", "Pinch Salt"], description: "Flavors of banana bread! Banana adds sweetness/creaminess, with warm spices.\n\nIncredible in smoothies, oatmeal, or sipped alone. Comforting.", nutrition: { calories: 110, fat_g: 8, saturated_fat_g: 0.9, carbs_g: 8, fiber_g: 1, sugars_g: 5, protein_g: 5, calcium_mg: 25, vitamin_d_iu: 0, iron_mg: 1.6, potassium_mg: 230 } },
    { id: "seed001", name: "Triple Seed Sunshine", ingredients: ["1/3 cup Pumpkin Seeds (Pepitas)", "1/3 cup Sunflower Seeds", "1/3 cup Hemp Hearts"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Vanilla Extract", "Pinch Salt"], description: "Nutty & nutrient-packed from three seeds. Balanced flavor, good minerals.\n\nGreat nut-free alternative. Use in smoothies, granola, savory recipes.", nutrition: { calories: 110, fat_g: 9, saturated_fat_g: 1, carbs_g: 5, fiber_g: 1, sugars_g: 3, protein_g: 4, calcium_mg: 25, vitamin_d_iu: 0, iron_mg: 1.5, potassium_mg: 150 } },
    { id: "seed002", name: "Pumpkin Spice Seed Delight", ingredients: ["1/2 cup Pumpkin Seeds", "1/4 cup Sunflower Seeds"], flavorings: ["1 tsp Pumpkin Pie Spice", "1.5 tbsp Maple Syrup", "1/4 tsp Vanilla Extract"], description: "Taste of autumn! Creamy pumpkin/sunflower milk with warming spice.\n\nPerfect for fall lattes, oatmeal, seasonal baking.", nutrition: { calories: 100, fat_g: 8, saturated_fat_g: 1, carbs_g: 6, fiber_g: 1, sugars_g: 4, protein_g: 3.5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 1.6, potassium_mg: 140 } },
    { id: "seed003", name: "Chia Charge Seed Milk", ingredients: ["1/2 cup Chia Seeds", "1/2 cup Sunflower Seeds"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Cinnamon"], description: "Thick and nutritious! Chia creates gel-like consistency. Needs a good shake.\n\nGreat for puddings or adding fiber/thickness to smoothies.", nutrition: { calories: 90, fat_g: 6.5, saturated_fat_g: 0.7, carbs_g: 8, fiber_g: 4, sugars_g: 3, protein_g: 3.5, calcium_mg: 100, vitamin_d_iu: 0, iron_mg: 1.5, potassium_mg: 100 } },
    { id: "nutblend001", name: "Almond Cashew Dream", ingredients: ["1/2 cup Raw Almonds", "1/2 cup Raw Cashews"], flavorings: ["1 tbsp Maple Syrup", "1/4 tsp Vanilla Extract", "Pinch Salt"], description: "Best of both worlds! Classic almond taste with incredible cashew creaminess.\n\nFantastic all-around milk. Use anywhere for richness. Superb in coffee.", nutrition: { calories: 75, fat_g: 6, saturated_fat_g: 0.8, carbs_g: 4.5, fiber_g: 1, sugars_g: 3, protein_g: 2.5, calcium_mg: 40, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 75 } },
    { id: "nutblend002", name: "Macadamia Hazelnut Luxe", ingredients: ["1/2 cup Raw Macadamia Nuts", "1/2 cup Raw Hazelnuts"], flavorings: ["1 tbsp Honey", "1/4 tsp Almond Extract (optional)", "Pinch Salt"], description: "Pure indulgence! Buttery macadamias meet aromatic hazelnuts. Naturally slightly sweet.\n\nAmazing coffee creamer, warmed drink, elevates desserts. High-fat treat!", nutrition: { calories: 140, fat_g: 14, saturated_fat_g: 2, carbs_g: 4, fiber_g: 1.5, sugars_g: 2.5, protein_g: 2, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 0.7, potassium_mg: 100 } },
    { id: "nutblend003", name: "Walnut Wonder", ingredients: ["1 cup Raw Walnuts (lightly toasted optional)"], flavorings: ["1 tbsp Maple Syrup", "1/4 tsp Cinnamon", "Pinch Salt"], description: "Distinctive, earthy walnuts, rich in Omega-3s. Cinnamon adds warmth.\n\nGood in smoothies, oatmeal, or savory recipes.", nutrition: { calories: 110, fat_g: 10, saturated_fat_g: 1, carbs_g: 5, fiber_g: 1, sugars_g: 3.5, protein_g: 2.5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 70 } },
    { id: "nutblend004", name: "ABC Milk (Almond, Brazil, Cashew)", ingredients: ["1/2 cup Raw Almonds", "1/4 cup Raw Brazil Nuts", "1/4 cup Raw Cashews"], flavorings: ["1 tbsp Agave Nectar", "1/4 tsp Vanilla", "Pinch Salt"], description: "Powerhouse blend, high in selenium from Brazil nuts! Creamy & nutty.\n\nExcellent nutritional boost. Use Brazil nuts sparingly.", nutrition: { calories: 100, fat_g: 9, saturated_fat_g: 1.5, carbs_g: 4, fiber_g: 1, sugars_g: 3, protein_g: 3, calcium_mg: 50, vitamin_d_iu: 0, iron_mg: 0.7, potassium_mg: 110 } },
    { id: "grain001", name: "Oat & Rice Serenity", ingredients: ["1/2 cup Rolled Oats", "1/2 cup Cooked Brown Rice"], flavorings: ["1 tbsp Agave Nectar", "1/4 tsp Vanilla Extract", "Pinch Salt"], description: "Mild, smooth, easily digestible milk blending oats and rice. Great for sensitive systems.\n\nNeutral flavor, perfect for everyday use.", nutrition: { calories: 55, fat_g: 0.8, saturated_fat_g: 0.1, carbs_g: 11, fiber_g: 1, sugars_g: 3.5, protein_g: 1.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 40 } },
    { id: "mixed001", name: "Sunrise Blend (Oat, Almond, Sunflower)", ingredients: ["1/3 cup Rolled Oats", "1/3 cup Raw Almonds", "1/3 cup Sunflower Seeds"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Vanilla Extract", "Pinch Salt"], description: "Bright start! Creamy oats, nutty almonds, mineral-rich sunflower seeds. Well-rounded.\n\nExcellent all-purpose milk.", nutrition: { calories: 80, fat_g: 5, saturated_fat_g: 0.5, carbs_g: 7, fiber_g: 1.5, sugars_g: 3, protein_g: 3, calcium_mg: 30, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 90 } },
    { id: "mixed002", name: "Midnight Velvet (Cashew, Hemp, Cocoa)", ingredients: ["1/2 cup Raw Cashews", "1/4 cup Hemp Hearts"], flavorings: ["2 tbsp Cocoa Powder", "1.5 tbsp Maple Syrup", "1/4 tsp Vanilla", "Pinch Salt"], description: "Rich, dark, velvety smooth. Creamy cashews & hemp with decadent chocolate.\n\nPerfect standalone drink, hot/cold. Great chia pudding/mocha base.", nutrition: { calories: 115, fat_g: 8.5, saturated_fat_g: 1.5, carbs_g: 8, fiber_g: 2, sugars_g: 4, protein_g: 4.5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 1.5, potassium_mg: 180 } },
    { id: "mixed003", name: "Tropical Power Mix (Coconut, Hemp, Pineapple)", ingredients: ["1/2 cup Unsweetened Shredded Coconut", "1/4 cup Hemp Hearts"], flavorings: ["1/4 cup Pineapple Chunks (fresh or frozen)", "1 tsp Agave Nectar (optional)", "Pinch Salt"], description: "Taste of the tropics with a protein punch! Creamy coconut and hemp meet tangy pineapple.\n\nFantastic smoothie base or chilled drink.", nutrition: { calories: 100, fat_g: 8.5, saturated_fat_g: 6.5, carbs_g: 5, fiber_g: 1, sugars_g: 3, protein_g: 3, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 1, potassium_mg: 120 } },
    { id: "pistachio001", name: "Emerald Pistachio Milk", ingredients: ["1 cup Raw Pistachios (shelled)"], flavorings: ["1 tbsp Honey", "1/4 tsp Cardamom (optional)", "Pinch Salt"], description: "Unique, elegant milk with light green hue and distinct pistachio flavor. Cardamom adds aroma.\n\nWonderful for special occasions, desserts, baking. Gourmet.", nutrition: { calories: 95, fat_g: 7.5, saturated_fat_g: 0.9, carbs_g: 6, fiber_g: 1.5, sugars_g: 4, protein_g: 3, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 150 } },
    { id: "soy001", name: "Classic Homemade Soy", ingredients: ["1/2 cup Dried Soybeans (soaked overnight, skins removed optional)"], flavorings: ["1 tbsp Maple Syrup (optional)", "Pinch Salt"], description: "Make your own soy milk! Soaking/deskinning gives cleaner flavor. Complete plant protein.\n\nVersatile. Ensure beans cook fully if machine doesn't heat.", nutrition: { calories: 60, fat_g: 3, saturated_fat_g: 0.4, carbs_g: 4, fiber_g: 1, sugars_g: 1, protein_g: 5, calcium_mg: 40, vitamin_d_iu: 0, iron_mg: 1, potassium_mg: 180 } },
    { id: "rice001", name: "Gentle Rice Milk", ingredients: ["1 cup Cooked Brown Rice (or white)"], flavorings: ["1 tbsp Agave Nectar", "1/2 tsp Vanilla Extract", "Pinch Salt"], description: "Very light, naturally sweet, easily digestible. Often hypoallergenic.\n\nGood for allergies. Thin texture best for drinking/light smoothies.", nutrition: { calories: 70, fat_g: 1, saturated_fat_g: 0.1, carbs_g: 14, fiber_g: 0.5, sugars_g: 6, protein_g: 0.5, calcium_mg: 5, vitamin_d_iu: 0, iron_mg: 0.2, potassium_mg: 20 } },
    { id: "walnut001", name: "Toasted Walnut Wonder", ingredients: ["1 cup Walnuts (lightly toasted optional)"], flavorings: ["1 tbsp Maple Syrup", "1/4 tsp Cinnamon", "Pinch Salt"], description: "Rich and robust! Earthy walnuts packed with Omega-3s. Cinnamon adds warmth.\n\nGreat in coffee, smoothies, savory sauces.", nutrition: { calories: 110, fat_g: 10, saturated_fat_g: 1, carbs_g: 5, fiber_g: 1, sugars_g: 3.5, protein_g: 2.5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 70 } },
    { id: "almond008", name: "Almond Butter Bliss", ingredients: ["1 cup Raw Almonds"], flavorings: ["1 tbsp Almond Butter", "1 tsp Maple Syrup", "Pinch Salt"], description: "Extra nutty richness by adding almond butter directly! Creates a thicker, more intensely flavored almond milk.\n\nExcellent for smoothies where extra body is desired, or as a decadent base for hot drinks.", nutrition: { calories: 95, fat_g: 8, saturated_fat_g: 0.7, carbs_g: 4.5, fiber_g: 1.5, sugars_g: 3.5, protein_g: 3.5, calcium_mg: 80, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 90 } },
    { id: "almond009", name: "Toasted Almond Delight", ingredients: ["1 cup Raw Almonds, lightly toasted"], flavorings: ["1 tbsp Maple Syrup", "1/4 tsp Almond Extract", "Pinch Salt"], description: "Toasting the almonds before blending unlocks a deeper, nuttier, more aromatic flavor profile. A simple step for a big impact.\n\nWonderful in coffee or enjoyed plain to appreciate the toasted notes. Gives baked goods a richer flavor.", nutrition: { calories: 70, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 4.5, fiber_g: 1, sugars_g: 3, protein_g: 2, calcium_mg: 70, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 60 } },
    { id: "almond010", name: "Berry Almond Fusion", ingredients: ["1 cup Raw Almonds"], flavorings: ["1/4 cup Mixed Berries (frozen)", "1 tsp Honey", "Pinch Salt"], description: "A vibrant blend of creamy almond milk with the antioxidant power and tanginess of mixed berries.\n\nCreates a beautiful pastel color. Perfect for a light breakfast drink or a healthy kids' treat.", nutrition: { calories: 80, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 8, fiber_g: 1.5, sugars_g: 6, protein_g: 2.5, calcium_mg: 65, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 80 } },
    { id: "almond011", name: "Almond Joy Inspired", ingredients: ["1 cup Raw Almonds"], flavorings: ["2 tbsp Unsweetened Shredded Coconut", "1 tbsp Cocoa Powder", "1.5 tbsp Maple Syrup", "Pinch Salt"], description: "Captures the essence of the candy bar! A delicious blend of almond, coconut, and chocolate.\n\nServe chilled for a treat. Blend with banana for a smoothie or add a shot of espresso for a mocha.", nutrition: { calories: 100, fat_g: 7, saturated_fat_g: 1.5, carbs_g: 8, fiber_g: 2.5, sugars_g: 4, protein_g: 3, calcium_mg: 70, vitamin_d_iu: 0, iron_mg: 0.9, potassium_mg: 140 } },
    { id: "almond012", name: "Orange Creamsicle Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["1 tsp Orange Zest", "1 tbsp Orange Juice (fresh)", "1/2 tsp Vanilla Extract", "1 tbsp Maple Syrup"], description: "A nostalgic flavor combination! Creamy almond milk with bright orange citrus notes and vanilla.\n\nVery refreshing served cold on a summer day. Also great in smoothies or even drizzled over pancakes.", nutrition: { calories: 75, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 6, fiber_g: 1, sugars_g: 4.5, protein_g: 2, calcium_mg: 70, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 75 } },
    { id: "cashew005", name: "Golden Cashew Latte Base", ingredients: ["1 cup Raw Cashews"], flavorings: ["1 tsp Turmeric", "1/2 tsp Cinnamon", "1/4 tsp Ginger", "Pinch Black Pepper", "1 tbsp Honey"], description: "A super creamy base for a golden milk latte. Anti-inflammatory spices blend perfectly with rich cashew.\n\nJust warm gently and add sweetener to taste. Optional: froth for a cafe-style experience.", nutrition: { calories: 90, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 7, fiber_g: 1, sugars_g: 5, protein_g: 2.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 1.0, potassium_mg: 110 } },
    { id: "cashew006", name: "Chocolate Hazelnut Cashew", ingredients: ["1/2 cup Raw Cashews", "1/2 cup Raw Hazelnuts"], flavorings: ["2 tbsp Cocoa Powder", "1.5 tbsp Maple Syrup", "1/4 tsp Vanilla"], description: "Like a healthy liquid Nutella! The combination of hazelnut, cashew, and cocoa is irresistible.\n\nDelicious on its own, hot or cold. Fantastic base for mochas or chocolate desserts.", nutrition: { calories: 120, fat_g: 9, saturated_fat_g: 1, carbs_g: 8, fiber_g: 2, sugars_g: 4, protein_g: 3, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 1.0, potassium_mg: 130 } },
    { id: "cashew007", name: "Date Sweetened Cashew", ingredients: ["1 cup Raw Cashews"], flavorings: ["2 Medjool Dates (pitted)", "1/2 tsp Vanilla", "Pinch Salt"], description: "Naturally sweetened with whole dates! Offers caramel notes and extra fiber compared to refined sweeteners.\n\nGreat all-purpose milk with a pleasant, mild sweetness. Perfect for those avoiding syrups or sugar.", nutrition: { calories: 95, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 9, fiber_g: 1.5, sugars_g: 6, protein_g: 2.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.9, potassium_mg: 120 } },
    { id: "cashew008", name: "Savory Herb Cashew Cream Base", ingredients: ["1 cup Raw Cashews"], flavorings: ["1 clove Garlic (optional)", "1 tsp Nutritional Yeast", "1/4 tsp Dried Dill (or other herb)", "Pinch Onion Powder", "Pinch Salt", "Pinch Black Pepper"], description: "Not all milk needs to be sweet! This is a base for creamy savory sauces or dips. Nutritional yeast adds cheesy flavor.\n\nBlend into pasta sauces, use as a base for vegan sour cream or ranch, or thicken soups. Do not sweeten!", nutrition: { calories: 75, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 3, fiber_g: 1, sugars_g: 0.5, protein_g: 3, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 95 } },
    { id: "oat006", name: "Maple Brown Sugar Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1.5 tbsp Brown Sugar (packed)", "1 tbsp Maple Syrup", "1/4 tsp Vanilla", "Pinch Salt"], description: "Classic comforting flavors reminiscent of oatmeal cookies. Deep molasses notes from brown sugar pair with maple.\n\nExcellent for baking, pouring over warm fruit crumble, or making decadent oatmeal.", nutrition: { calories: 85, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 18, fiber_g: 1, sugars_g: 8, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 70 } },
    { id: "oat007", name: "Apple Cinnamon Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1/4 cup Unsweetened Applesauce", "1 tsp Cinnamon", "1 tsp Maple Syrup", "Pinch Salt"], description: "The taste of apple pie in a glass! Natural sweetness and flavor from applesauce with warming cinnamon.\n\nGreat served warm, especially in autumn. Also delicious chilled or added to smoothies.", nutrition: { calories: 70, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 14, fiber_g: 1.5, sugars_g: 5, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 65 } },
    { id: "oat008", name: "Coffee Lover's Oat Milk", ingredients: ["1 cup Rolled Oats"], flavorings: ["1-2 tsp Instant Coffee Granules", "1 tbsp Maple Syrup", "Pinch Salt"], description: "Get your coffee fix right in your milk! Creamy oat milk infused with coffee flavor.\n\nPerfect base for iced coffee or blended coffee drinks. Adjust coffee amount to your strength preference.", nutrition: { calories: 60, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 11, fiber_g: 1, sugars_g: 4, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 55 } },
    { id: "oat009", name: "Horchata Inspired Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1 tsp Cinnamon", "1/2 tsp Vanilla Extract", "1.5 tbsp Agave Nectar", "Pinch Salt"], description: "A plant-based take on the classic Mexican rice drink, using oats! Creamy, cinnamon-spiced, and refreshing.\n\nBest served chilled, perhaps over ice. A delightful alternative.", nutrition: { calories: 70, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 14, fiber_g: 1, sugars_g: 5, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 50 } },
    { id: "coconut010", name: "Coconut Vanilla Bean", ingredients: ["1 cup Shredded Coconut"], flavorings: ["1 tsp Vanilla Bean Paste", "1 tbsp Agave"], description: "Intense vanilla bean flavor meets tropical coconut.\n\nAdds a gourmet touch to smoothies, desserts, or coffee.", nutrition: { calories: 80, fat_g: 6.5, saturated_fat_g: 6, carbs_g: 5, fiber_g: 1, sugars_g: 4, protein_g: 0.5, calcium_mg: 5, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 50 } },
    { id: "hemp008", name: "Maple Cinnamon Hemp", ingredients: ["1/2 cup Hemp Hearts"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Cinnamon"], description: "Warming cinnamon complements earthy hemp, sweetened with maple.\n\nGood addition to fall smoothies or warm drinks.", nutrition: { calories: 95, fat_g: 8, saturated_fat_g: 0.8, carbs_g: 5, fiber_g: 1, sugars_g: 3.5, protein_g: 5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 1.6, potassium_mg: 185 } },
    { id: "seed008", name: "Maple Sunflower", ingredients: ["1 cup Sunflower Seeds"], flavorings: ["1.5 tbsp Maple Syrup", "Pinch Salt"], description: "Simple, slightly sweet sunflower seed milk.\n\nA good staple nut-free milk sweetened naturally.", nutrition: { calories: 110, fat_g: 8.5, saturated_fat_g: 0.9, carbs_g: 7, fiber_g: 1.5, sugars_g: 5, protein_g: 3.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 1.0, potassium_mg: 100 } },
    { id: "nutblend010", name: "Almond Walnut Maple", ingredients: ["1/2 cup Almonds", "1/2 cup Walnuts"], flavorings: ["1 tbsp Maple Syrup", "Pinch Salt"], description: "Combines the popular almond base with the Omega-3 benefits and flavor of walnuts.\n\nGood all-around blend for smoothies and oatmeal.", nutrition: { calories: 95, fat_g: 8, saturated_fat_g: 0.7, carbs_g: 5.5, fiber_g: 1.5, sugars_g: 3.5, protein_g: 2.5, calcium_mg: 45, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 65 } },
    { id: "grain004", name: "Plain Cooked Quinoa Milk", ingredients: ["1 cup Cooked Quinoa"], flavorings: ["Pinch Salt"], description: "Milk made solely from quinoa. Offers complete protein. Mild, slightly grassy flavor.\n\nGood base for savory applications or protein-boosted smoothies.", nutrition: { calories: 40, fat_g: 1.5, saturated_fat_g: 0.2, carbs_g: 6, fiber_g: 1, sugars_g: 0.5, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 60 } }, // Quinoa base
    { id: "mixed009", name: "Cashew Coconut Cocoa", ingredients: ["1/2 cup Cashews", "1/2 cup Shredded Coconut"], flavorings: ["2 tbsp Cocoa Powder", "1 tbsp Honey"], description: "Rich, creamy, chocolatey blend of cashew and coconut.\n\nDecadent treat hot or cold, great for desserts.", nutrition: { calories: 115, fat_g: 9.5, saturated_fat_g: 7.2, carbs_g: 8, fiber_g: 2, sugars_g: 5, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 1.0, potassium_mg: 120 } },
    { id: "mixed010", name: "Oat Sunflower Vanilla", ingredients: ["1/2 cup Rolled Oats", "1/2 cup Sunflower Seeds"], flavorings: ["1 tsp Vanilla", "1 tbsp Maple Syrup"], description: "Creamy oat meets nutty sunflower with a classic vanilla flavor.\n\nGood nut-free vanilla milk alternative.", nutrition: { calories: 85, fat_g: 5, saturated_fat_g: 0.6, carbs_g: 9, fiber_g: 1.5, sugars_g: 4, protein_g: 3, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 75 } },
    { id: "pistachio002", name: "Vanilla Pistachio Swirl", ingredients: ["1 cup Raw Pistachios"], flavorings: ["1/2 tsp Vanilla Extract", "1 tbsp Agave Nectar"], description: "Simple vanilla enhances the unique flavor of pistachio milk without overpowering it.\n\nA light, elegant milk perfect for drinking plain or adding to delicate recipes.", nutrition: { calories: 90, fat_g: 7.5, saturated_fat_g: 0.9, carbs_g: 5, fiber_g: 1.5, sugars_g: 3.5, protein_g: 3, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 150 } },
    { id: "macadamia001", name: "Pure Macadamia Cream", ingredients: ["1 cup Raw Macadamia Nuts"], flavorings: ["Pinch Salt", "1 tsp Maple Syrup (optional)"], description: "Incredibly rich and buttery, pure macadamia milk is a luxurious treat. High in healthy fats.\n\nUse sparingly as a creamer or in rich desserts. A little goes a long way.", nutrition: { calories: 160, fat_g: 16, saturated_fat_g: 2.5, carbs_g: 3, fiber_g: 2, sugars_g: 1.5, protein_g: 1.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 70 } }, // High Cal/Fat
    { id: "hazelnut001", name: "Classic Hazelnut Milk", ingredients: ["1 cup Raw Hazelnuts"], flavorings: ["1 tbsp Maple Syrup", "1/4 tsp Vanilla"], description: "Distinctive, aromatic hazelnut flavor. Reminiscent of popular coffee creamers but homemade!\n\nFantastic in coffee, hot chocolate, or used in baking for a nutty depth.", nutrition: { calories: 95, fat_g: 8.5, saturated_fat_g: 0.6, carbs_g: 5, fiber_g: 1.5, sugars_g: 3.5, protein_g: 2, calcium_mg: 30, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 90 } },
    { id: "pecan001", name: "Vanilla Pecan Pleasure", ingredients: ["1 cup Raw Pecans"], flavorings: ["1/2 tsp Vanilla Extract", "1 tbsp Honey"], description: "Buttery pecans blended into a smooth milk with vanilla and honey notes. A comforting, rich flavor.\n\nGreat for fall recipes, sweetening coffee, or enjoying as a dessert-like drink.", nutrition: { calories: 130, fat_g: 12, saturated_fat_g: 1, carbs_g: 6, fiber_g: 1.5, sugars_g: 4.5, protein_g: 1.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 60 } },
    { id: "brazilnut001", name: "Selenium Boost Brazil Nut", ingredients: ["1/2 cup Raw Brazil Nuts"], flavorings: ["1 tsp Maple Syrup", "Pinch Salt"], description: "Use Brazil nuts sparingly due to high selenium! This makes a creamy, nutrient-dense milk. Blend maybe with 1/2 cup cashews if too strong.\n\nGood way to get selenium, but limit intake. Blend with other nuts for milder flavor.", nutrition: { calories: 110, fat_g: 11, saturated_fat_g: 2.5, carbs_g: 3, fiber_g: 1, sugars_g: 1.5, protein_g: 2.5, calcium_mg: 25, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 100, selenium_mcg: 800 } }, // Added Selenium estimate - HIGH
    { id: "pumpkinseed001", name: "Simple Pepita Milk", ingredients: ["1 cup Pumpkin Seeds (Pepitas)"], flavorings: ["1 tbsp Agave Nectar", "Pinch Salt"], description: "A straightforward milk from pumpkin seeds, offering magnesium, zinc, and a nice green tint.\n\nGood nut-free option with a mild, slightly grassy flavor.", nutrition: { calories: 90, fat_g: 8, saturated_fat_g: 1.5, carbs_g: 3.5, fiber_g: 1, sugars_g: 2.5, protein_g: 4, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 2.0, potassium_mg: 120 } },
    { id: "sunflowerseed001", name: "Sunny Sunflower Milk", ingredients: ["1 cup Raw Sunflower Seeds"], flavorings: ["1 tbsp Honey", "1/4 tsp Vanilla"], description: "Affordable and readily available, sunflower seeds make a surprisingly creamy nut-free milk.\n\nGood all-purpose milk, especially useful in nut-free households or schools.", nutrition: { calories: 105, fat_g: 9, saturated_fat_g: 1, carbs_g: 5, fiber_g: 1.5, sugars_g: 3.5, protein_g: 3.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 1.0, potassium_mg: 100 } },
    { id: "flaxseed001", name: "Omega Rich Flax Milk", ingredients: ["1/2 cup Whole Flax Seeds"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Vanilla"], description: "High in Omega-3s and fiber. Will result in a thicker, slightly gelatinous milk. Shake well.\n\nBest used in smoothies where thickness is desired or for boosting fiber intake.", nutrition: { calories: 70, fat_g: 5, saturated_fat_g: 0.5, carbs_g: 6, fiber_g: 4, sugars_g: 3, protein_g: 2.5, calcium_mg: 30, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 90 } }, // High Fiber
    { id: "flavor001", name: "Hint of Mint Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["1/4 tsp Peppermint Extract", "1 tbsp Agave Nectar"], description: "A refreshing twist! Cool peppermint adds a clean finish to creamy almond milk.\n\nExcellent base for healthy mint-chocolate chip smoothies or a refreshing summer drink.", nutrition: { calories: 65, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 4.5, fiber_g: 1, sugars_g: 3.5, protein_g: 2, calcium_mg: 60, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 60 } },
    { id: "flavor002", name: "Hint of Lemon Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1 tsp Lemon Zest", "1 tbsp Maple Syrup"], description: "Bright lemon zest cuts through the richness of oat milk for a light, vibrant flavor.\n\nInteresting addition to smoothies or used in lemon-flavored baked goods.", nutrition: { calories: 60, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 11.5, fiber_g: 1, sugars_g: 4, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 55 } },
    { id: "flavor003", name: "Orange Spice Cashew", ingredients: ["1 cup Raw Cashews"], flavorings: ["1 tsp Orange Zest", "1/4 tsp Cinnamon", "1 tbsp Honey"], description: "Warm spice meets bright citrus in this creamy cashew milk.\n\nA delightful flavor for fall or winter, great served warm.", nutrition: { calories: 90, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 7, fiber_g: 0.5, sugars_g: 5.5, protein_g: 2.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 100 } },
    { id: "flavor004", name: "Maple Ginger Hemp", ingredients: ["1/2 cup Hemp Hearts"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Ground Ginger"], description: "Spicy ginger adds a pleasant warmth and zing to earthy hemp milk, balanced by maple.\n\nGood for digestion, nice served warm or added to tea.", nutrition: { calories: 90, fat_g: 8, saturated_fat_g: 0.8, carbs_g: 4.5, fiber_g: 0.5, sugars_g: 3, protein_g: 5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 1.6, potassium_mg: 190 } },
    { id: "blend005", name: "Almond Coconut Vanilla", ingredients: ["1/2 cup Raw Almonds", "1/2 cup Shredded Coconut"], flavorings: ["1/2 tsp Vanilla", "1 tbsp Maple"], description: "A smooth blend combining almond, coconut, and vanilla. Crowd-pleasing flavor.\n\nExcellent all-purpose milk, great substitute for dairy in many recipes.", nutrition: { calories: 70, fat_g: 6, saturated_fat_g: 3.2, carbs_g: 4, fiber_g: 1.5, sugars_g: 3, protein_g: 1.5, calcium_mg: 40, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 55 } },
    { id: "blend006", name: "Oat Hazelnut Boost", ingredients: ["3/4 cup Rolled Oats", "1/4 cup Raw Hazelnuts"], flavorings: ["1 tbsp Honey", "Pinch Salt"], description: "Adds the aromatic flavor of hazelnuts to creamy oat milk.\n\nNice in coffee or for making flavored oatmeal.", nutrition: { calories: 75, fat_g: 3, saturated_fat_g: 0.3, carbs_g: 11, fiber_g: 1.5, sugars_g: 4.5, protein_g: 2.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 70 } },
    { id: "blend007", name: "Cashew Sunflower Cream", ingredients: ["1/2 cup Raw Cashews", "1/2 cup Sunflower Seeds"], flavorings: ["1 tbsp Agave", "1/4 tsp Vanilla"], description: "Combines cashew creaminess with sunflower's nuttiness for a rich nut-free(ish) blend.\n\nGood base for creamy sauces or smoothies if avoiding almonds.", nutrition: { calories: 115, fat_g: 10, saturated_fat_g: 1.3, carbs_g: 6, fiber_g: 1, sugars_g: 4, protein_g: 4, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 1.2, potassium_mg: 130 } },
    { id: "blend008", name: "Pecan Oat Crumble", ingredients: ["1/2 cup Raw Pecans", "1/2 cup Rolled Oats"], flavorings: ["1 tbsp Maple Syrup", "1/2 tsp Cinnamon"], description: "Like a liquid pecan crumble topping! Buttery pecans meet oats and cinnamon.\n\nDelicious served warm or used as a base for apple crumble smoothies.", nutrition: { calories: 95, fat_g: 6.5, saturated_fat_g: 0.6, carbs_g: 8, fiber_g: 1.5, sugars_g: 4, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 65 } },
    { id: "blend009", name: "Walnut Hemp Omega", ingredients: ["1/2 cup Walnuts", "1/2 cup Hemp Hearts"], flavorings: ["1 tbsp Maple Syrup", "Pinch Salt"], description: "Maximizes Omega-3 content by combining walnuts and hemp seeds.\n\nNutrient-dense milk perfect for smoothies or adding healthy fats to your diet.", nutrition: { calories: 135, fat_g: 12.5, saturated_fat_g: 1.1, carbs_g: 4.5, fiber_g: 1, sugars_g: 3, protein_g: 5, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 1.0, potassium_mg: 125 } },
    { id: "blend010", name: "Coconut Almond Cocoa", ingredients: ["1/2 cup Raw Almonds", "1/2 cup Shredded Coconut"], flavorings: ["1.5 tbsp Cocoa Powder", "1.5 tbsp Agave"], description: "Another take on the Almond Joy flavor, using agave for sweetening.\n\nGreat chilled dessert drink or smoothie base.", nutrition: { calories: 95, fat_g: 7, saturated_fat_g: 3.2, carbs_g: 7.5, fiber_g: 2.5, sugars_g: 4.5, protein_g: 2, calcium_mg: 40, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 95 } },
    { id: "blend011", name: "Almond Oat Strawberry", ingredients: ["1/2 cup Almonds", "1/2 cup Rolled Oats"], flavorings: ["1/3 cup Strawberries", "1 tbsp Honey"], description: "Creamy, nutty, fruity, and pretty! A balanced blend for smoothies or drinking.\n\nWell-rounded flavor profile loved by many.", nutrition: { calories: 80, fat_g: 3.5, saturated_fat_g: 0.3, carbs_g: 11, fiber_g: 1.5, sugars_g: 6, protein_g: 2.5, calcium_mg: 40, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 90 } },
    { id: "blend012", name: "Cashew Coconut Lime", ingredients: ["1/2 cup Cashews", "1/2 cup Shredded Coconut"], flavorings: ["1 tbsp Lime Juice", "1 tsp Agave"], description: "Ultra-creamy cashew meets tropical coconut with zesty lime.\n\nExcellent base for Thai-inspired dishes or refreshing drinks.", nutrition: { calories: 100, fat_g: 9.5, saturated_fat_g: 7.2, carbs_g: 5, fiber_g: 1, sugars_g: 3, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 70 } },
    { id: "blend013", name: "Hemp Sunflower Cacao", ingredients: ["1/2 cup Hemp Hearts", "1/2 cup Sunflower Seeds"], flavorings: ["1.5 tbsp Cacao Powder (raw)", "1 tbsp Maple Syrup"], description: "Nut-free chocolate milk packed with protein/minerals. Cacao offers antioxidants.\n\nGreat for recovery or nutrient-dense chocolate milk.", nutrition: { calories: 125, fat_g: 10.5, saturated_fat_g: 1.1, carbs_g: 7, fiber_g: 2.5, sugars_g: 4, protein_g: 6, calcium_mg: 25, vitamin_d_iu: 0, iron_mg: 2.2, potassium_mg: 200 } },
    { id: "blend014", name: "Oat Pecan Spice", ingredients: ["3/4 cup Rolled Oats", "1/4 cup Pecans"], flavorings: ["1 tsp Cinnamon", "1/4 tsp Nutmeg", "1 tbsp Maple Syrup"], description: "Warming spices blended with creamy oats and buttery pecans.\n\nComforting flavor perfect for fall drinks or baking.", nutrition: { calories: 85, fat_g: 4, saturated_fat_g: 0.4, carbs_g: 12, fiber_g: 1.5, sugars_g: 5, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 75 } },
    { id: "blend015", name: "Pumpkin Seed Almond Vanilla", ingredients: ["1/2 cup Pumpkin Seeds", "1/2 cup Almonds"], flavorings: ["1/2 tsp Vanilla", "1 tbsp Agave"], description: "Combines pepita benefits with classic almond flavor and vanilla.\n\nNutrient-rich blend with magnesium, zinc, vitamin E.", nutrition: { calories: 95, fat_g: 8, saturated_fat_g: 1.0, carbs_g: 4, fiber_g: 1.5, sugars_g: 3, protein_g: 4, calcium_mg: 45, vitamin_d_iu: 0, iron_mg: 1.2, potassium_mg: 90 } },
    { id: "other001", name: "Pistachio Rose Dream", ingredients: ["1 cup Pistachios"], flavorings: ["1 tbsp Honey", "1/4 tsp Rose Water"], description: "Elegant and fragrant, a beautiful combination.\n\nPerfect for special occasions or adding to desserts.", nutrition: { calories: 100, fat_g: 7.5, saturated_fat_g: 0.9, carbs_g: 7.5, fiber_g: 1.5, sugars_g: 5.5, protein_g: 3, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 155 } },
    { id: "other002", name: "Macadamia Vanilla Bean", ingredients: ["1 cup Macadamia Nuts"], flavorings: ["1/2 Vanilla Bean, scraped", "1 tsp Maple Syrup"], description: "The ultimate luxury: rich macadamia with real vanilla bean.\n\nIncredible flavor for coffee or special treats.", nutrition: { calories: 165, fat_g: 16, saturated_fat_g: 2.5, carbs_g: 3.5, fiber_g: 2, sugars_g: 2, protein_g: 1.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 70 } },
    { id: "other003", name: "Hazelnut Honey Spice", ingredients: ["1 cup Hazelnuts"], flavorings: ["1.5 tbsp Honey", "1/2 tsp Cinnamon", "Pinch Nutmeg"], description: "Warm spices enhance the natural toastiness of hazelnuts.\n\nGreat served warm on a cold day.", nutrition: { calories: 110, fat_g: 8.5, saturated_fat_g: 0.6, carbs_g: 8, fiber_g: 1.5, sugars_g: 6, protein_g: 2, calcium_mg: 30, vitamin_d_iu: 0, iron_mg: 0.7, potassium_mg: 95 } },
    { id: "other004", name: "Pecan Maple Cream", ingredients: ["1 cup Pecans"], flavorings: ["1.5 tbsp Maple Syrup", "1/4 tsp Vanilla"], description: "Very rich and buttery pecan milk sweetened with maple.\n\nA dessert in itself or a base for pecan pie flavors.", nutrition: { calories: 130, fat_g: 12, saturated_fat_g: 1, carbs_g: 6, fiber_g: 1.5, sugars_g: 4.5, protein_g: 1.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 60 } },
    { id: "other005", name: "Spiced Pepita Milk", ingredients: ["1 cup Pumpkin Seeds"], flavorings: ["1 tsp Cinnamon", "1/4 tsp Ginger", "1 tbsp Maple Syrup"], description: "Warming spices complement the unique flavor of pumpkin seed milk.\n\nGood fall alternative to nut milks.", nutrition: { calories: 100, fat_g: 8, saturated_fat_g: 1.5, carbs_g: 5.5, fiber_g: 1, sugars_g: 3.5, protein_g: 4, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 2.1, potassium_mg: 125 } },
    { id: "other006", name: "Toasted Sunflower Vanilla", ingredients: ["1 cup Sunflower Seeds, toasted"], flavorings: ["1 tsp Vanilla", "1 tbsp Honey"], description: "Toasting sunflower seeds adds depth. Simple vanilla and honey enhance.\n\nNut-free option with a richer, toasted flavor.", nutrition: { calories: 115, fat_g: 9, saturated_fat_g: 1, carbs_g: 7, fiber_g: 1.5, sugars_g: 5, protein_g: 3.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 1.0, potassium_mg: 105 } },
    { id: "dessert001", name: "Tiramisu Inspired Cashew Milk", ingredients: ["1 cup Raw Cashews"], flavorings: ["1 tbsp Maple Syrup", "1 tsp Instant Coffee Granules", "1/4 tsp Cocoa Powder", "1/2 tsp Vanilla Extract", "Pinch Salt"], description: "Captures the essence of Tiramisu! Creamy cashew base with coffee, cocoa, and vanilla notes.\n\nServe chilled as a dessert drink, maybe with a ladyfinger on the side! Or use as a base for a tiramisu smoothie.", nutrition: { calories: 95, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 8, fiber_g: 1, sugars_g: 5, protein_g: 3, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 1.0, potassium_mg: 110 } },
    { id: "dessert002", name: "Choc Chip Cookie Dough Almond", ingredients: ["1 cup Raw Almonds", "1/4 cup Rolled Oats (for texture)"], flavorings: ["1.5 tbsp Brown Sugar", "1/2 tsp Vanilla Extract", "1 tbsp Mini Chocolate Chips (add AFTER blending if desired, or just for flavor profile)", "Pinch Salt"], description: "Tastes remarkably like cookie dough! Creamy almond-oat base with brown sugar and vanilla. Add mini chips at the end for texture if you like.\n\nAn indulgent treat! Best served cold. Note: Adding actual cookies might clog filter, this uses flavors.", nutrition: { calories: 100, fat_g: 5.5, saturated_fat_g: 0.8, carbs_g: 11, fiber_g: 1.5, sugars_g: 6, protein_g: 2.5, calcium_mg: 65, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 80 } }, // Estimate with chips
    { id: "dessert003", name: "Strawberry Shortcake Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1/3 cup Strawberries", "1 tsp Vanilla Extract", "1 tbsp Maple Syrup"], description: "Like liquid strawberry shortcake! Creamy oats, sweet strawberries, and vanilla.\n\nDrizzle over actual shortcake or enjoy as a sweet treat.", nutrition: { calories: 75, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 15.5, fiber_g: 1.5, sugars_g: 7.5, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 80 } },
    { id: "dessert004", name: "Key Lime Pie Coconut", ingredients: ["1 cup Shredded Coconut"], flavorings: ["1.5 tbsp Lime Juice", "1 tsp Lime Zest", "1 tbsp Maple Syrup", "1/4 tsp Vanilla"], description: "Tangy lime and creamy coconut reminiscent of key lime pie.\n\nRefreshing dessert drink or smoothie base.", nutrition: { calories: 85, fat_g: 6.5, saturated_fat_g: 6, carbs_g: 6, fiber_g: 1, sugars_g: 5, protein_g: 0.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 60 } },
    { id: "dessert005", name: "Birthday Cake Cashew", ingredients: ["1 cup Raw Cashews"], flavorings: ["1 tsp Vanilla Extract", "1/2 tsp Almond Extract", "1.5 tbsp Agave Nectar", "1 tbsp Rainbow Sprinkles (optional, add AFTER blending)"], description: "Funfetti in a glass! Creamy cashew with classic birthday cake extracts. Sprinkles optional!\n\nA fun treat for celebrations or just because.", nutrition: { calories: 100, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 9, fiber_g: 0.5, sugars_g: 7, protein_g: 2.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 90 } }, // Sprinkles negligible unless many added
    { id: "dessert006", name: "Apple Crumble Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1/4 cup Unsweetened Applesauce", "1 tsp Cinnamon", "1/4 tsp Nutmeg", "1 tbsp Brown Sugar"], description: "Warm apples and spices make this taste like apple crumble topping.\n\nDelicious warm or cold, great with granola.", nutrition: { calories: 85, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 18, fiber_g: 1.5, sugars_g: 7, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.7, potassium_mg: 75 } },
    { id: "dessert007", name: "Salted Caramel Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["3 Medjool Dates, pitted", "1/2 tsp Vanilla", "1/4 tsp Coarse Sea Salt"], description: "Rich caramel flavor from dates balanced with sea salt.\n\nAn addictive sweet and salty treat. Great coffee addition.", nutrition: { calories: 95, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 12, fiber_g: 2, sugars_g: 9, protein_g: 2.5, calcium_mg: 70, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 120 } }, // Dates add sugar/K/fiber
    { id: "dessert008", name: "Pecan Pie Cream", ingredients: ["1 cup Raw Pecans"], flavorings: ["1.5 tbsp Maple Syrup", "1/2 tsp Vanilla", "Pinch Cinnamon"], description: "All the flavors of pecan pie filling in a creamy milk.\n\nIndulgent drink or use in dessert recipes.", nutrition: { calories: 130, fat_g: 12, saturated_fat_g: 1, carbs_g: 6, fiber_g: 1.5, sugars_g: 4.5, protein_g: 1.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 60 } },
    { id: "dessert009", name: "Gingerbread Spice Oat", ingredients: ["1 cup Rolled Oats"], flavorings: ["1 tbsp Molasses", "1 tsp Ground Ginger", "1/2 tsp Cinnamon", "Pinch Clove"], description: "Classic gingerbread flavors perfect for the holidays.\n\nServe warm for a cozy festive treat.", nutrition: { calories: 75, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 16, fiber_g: 1.5, sugars_g: 6, protein_g: 2, calcium_mg: 25, vitamin_d_iu: 0, iron_mg: 1.0, potassium_mg: 100 } }, // Molasses adds iron/calcium/K
    { id: "dessert010", name: "Chocolate Orange Almond", ingredients: ["1 cup Raw Almonds"], flavorings: ["1.5 tbsp Cocoa Powder", "1 tsp Orange Zest", "1 tbsp Maple Syrup"], description: "Classic pairing of rich chocolate and bright orange zest.\n\nA sophisticated flavor great for sipping or adding to mochas.", nutrition: { calories: 85, fat_g: 5.5, saturated_fat_g: 0.6, carbs_g: 8, fiber_g: 2, sugars_g: 4, protein_g: 2.5, calcium_mg: 70, vitamin_d_iu: 0, iron_mg: 0.8, potassium_mg: 125 } },
    { id: "seasonal001", name: "Spring Blossom (Almond Rose)", ingredients: ["1 cup Raw Almonds"], flavorings: ["1 tbsp Honey", "1/4 tsp Rose Water"], description: "Light, floral, and refreshing, evoking springtime.\n\nServe chilled, perhaps with berries.", nutrition: { calories: 75, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 6, fiber_g: 1, sugars_g: 5, protein_g: 2, calcium_mg: 60, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 65 } },
    { id: "seasonal002", name: "Summer Berry Blend (Oat Coconut Berry)", ingredients: ["1/2 cup Oats", "1/2 cup Shredded Coconut"], flavorings: ["1/3 cup Mixed Berries", "1 tbsp Agave"], description: "A light and fruity blend perfect for hot weather.\n\nGreat smoothie base or refreshing drink.", nutrition: { calories: 80, fat_g: 4, saturated_fat_g: 3.1, carbs_g: 10.5, fiber_g: 1.5, sugars_g: 6, protein_g: 1.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 60 } },
    { id: "seasonal003", name: "Autumn Harvest (Pecan Oat Spice)", ingredients: ["1/2 cup Pecans", "1/2 cup Oats"], flavorings: ["1 tbsp Maple Syrup", "1 tsp Pumpkin Pie Spice"], description: "Warming spices, buttery pecans, creamy oats - quintessential fall.\n\nServe warm, add to coffee or oatmeal.", nutrition: { calories: 100, fat_g: 6.5, saturated_fat_g: 0.6, carbs_g: 9.5, fiber_g: 1.5, sugars_g: 4.5, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 65 } },
    { id: "seasonal004", name: "Winter Warmer (Cashew Ginger Molasses)", ingredients: ["1 cup Cashews"], flavorings: ["1 tbsp Molasses", "1/2 tsp Ground Ginger", "1/4 tsp Cinnamon"], description: "Deep, warming flavors perfect for cold nights.\n\nExcellent served hot, maybe with a splash of brandy for adults.", nutrition: { calories: 100, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 9, fiber_g: 1, sugars_g: 5.5, protein_g: 2.5, calcium_mg: 25, vitamin_d_iu: 0, iron_mg: 1.2, potassium_mg: 140 } },
    { id: "unique001", name: "Black Sesame Zen", ingredients: ["1 cup Black Sesame Seeds (toasted optional)"], flavorings: ["1 tbsp Honey or Maple Syrup"], description: "Nutty, deeply savory, and slightly bitter flavor with a striking grey color.\n\nUsed in Asian desserts and drinks. An acquired but rewarding taste.", nutrition: { calories: 110, fat_g: 9, saturated_fat_g: 1.3, carbs_g: 6, fiber_g: 2, sugars_g: 3.5, protein_g: 3, calcium_mg: 180, vitamin_d_iu: 0, iron_mg: 2.5, potassium_mg: 80 } }, // Sesame high calcium/iron
    { id: "unique002", name: "Smoked Paprika Almond (Savory)", ingredients: ["1 cup Raw Almonds"], flavorings: ["1/2 tsp Smoked Paprika", "1/4 tsp Garlic Powder", "Pinch Salt"], description: "A savory milk with a smoky kick!\n\nUse as a base for creamy soups, sauces, or even savory 'milkshakes'.", nutrition: { calories: 50, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 1.5, fiber_g: 1, sugars_g: 0.5, protein_g: 2, calcium_mg: 60, vitamin_d_iu: 0, iron_mg: 0.4, potassium_mg: 65 } },
    { id: "unique003", name: "Beet Red Oat Latte", ingredients: ["1 cup Rolled Oats"], flavorings: ["1 tbsp Cooked Beet Puree", "1 tsp Honey", "Pinch Ginger"], description: "Vibrant red color and earthy sweetness from beets.\n\nInteresting latte base or smoothie addition. Pairs well with ginger.", nutrition: { calories: 60, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 11.5, fiber_g: 1.5, sugars_g: 5, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 70 } }, // Beets add folate etc.
    { id: "unique004", name: "Carrot Cake Cashew", ingredients: ["1 cup Raw Cashews"], flavorings: ["1/4 cup Shredded Carrot", "1/2 tsp Cinnamon", "1/4 tsp Nutmeg", "1 tbsp Maple Syrup"], description: "All the flavors of carrot cake! Sweet carrots, warm spices, creamy cashew.\n\nDelicious chilled drink or smoothie base.", nutrition: { calories: 90, fat_g: 6.5, saturated_fat_g: 1.2, carbs_g: 7.5, fiber_g: 1, sugars_g: 5, protein_g: 2.5, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.9, potassium_mg: 115 } }, // Carrot adds Vit A
    { id: "unique005", name: "Earl Grey Almond Milk", ingredients: ["1 cup Raw Almonds"], flavorings: ["1 Earl Grey Tea Bag (steep in warm water briefly, add water to pitcher)", "1 tsp Honey", "Pinch Lemon Zest (optional)"], description: "Infused with the bergamot aroma of Earl Grey tea.\n\nUnique base for London Fog lattes or enjoyed chilled.", nutrition: { calories: 75, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 6, fiber_g: 1, sugars_g: 5, protein_g: 2, calcium_mg: 60, vitamin_d_iu: 0, iron_mg: 0.3, potassium_mg: 65 } }, // Tea negligible nutritionally
    { id: "final001", name: "Simple Toasted Oat", ingredients: ["1 cup Rolled Oats, lightly toasted"], flavorings: ["1 tbsp Maple Syrup"], description: "Toasting oats brings out a nuttier, deeper flavor than raw.\n\nGreat alternative to standard oat milk.", nutrition: { calories: 65, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 12, fiber_g: 1, sugars_g: 4, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 50 } },
    { id: "final002", name: "Cashew Almond Vanilla Date", ingredients: ["1/2 cup Cashews", "1/2 cup Almonds"], flavorings: ["2 Medjool Dates, pitted", "1/2 tsp Vanilla"], description: "Creamy blend naturally sweetened with dates.\n\nWell-rounded, satisfying all-purpose milk.", nutrition: { calories: 90, fat_g: 6, saturated_fat_g: 0.8, carbs_g: 9, fiber_g: 1.5, sugars_g: 6.5, protein_g: 2.5, calcium_mg: 45, vitamin_d_iu: 0, iron_mg: 0.7, potassium_mg: 100 } },
    { id: "final003", name: "Coconut Oat Creamer", ingredients: ["1/2 cup Shredded Coconut", "1/2 cup Rolled Oats"], flavorings: ["1 tsp Vanilla", "1 tsp Maple (optional)"], description: "Combines coconut richness with oat creaminess for a lovely creamer.\n\nGood dairy-free option for coffee or tea.", nutrition: { calories: 70, fat_g: 4, saturated_fat_g: 3.1, carbs_g: 7.5, fiber_g: 1.5, sugars_g: 3, protein_g: 1.5, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 50 } },
    { id: "dessert011", name: "Chocolate Chip Cookie Almond Milk", ingredients: ["1 cup Raw Almonds", "1 cup Crushed Chocolate Chip Cookies (approx 4-6 cookies, results vary!)"], flavorings: ["1/4 tsp Vanilla Extract", "(Adjust sweetness AFTER tasting, cookies add sugar)"], description: "Super indulgent! Blends actual cookies into the milk. Will likely be thick and needs straining. The ultimate dessert milk!\n\nNote: HIGHLY experimental. May require extra water or less cookie. Strain well after blending. Treat as a dessert!", nutrition: { calories: 250, fat_g: 12, saturated_fat_g: 3.5, carbs_g: 30, fiber_g: 2, sugars_g: 18, protein_g: 4, calcium_mg: 80, vitamin_d_iu: 0, iron_mg: 1.5, potassium_mg: 150 } }, // VERY rough estimate based on cookies
    { id: "dessert012", name: "Snickerdoodle Oat Milk", ingredients: ["1 cup Rolled Oats"], flavorings: ["1.5 tbsp Maple Syrup", "1 tsp Cinnamon", "1/4 tsp Cream of Tartar (optional, for tang)", "1/2 tsp Vanilla"], description: "Tastes like a snickerdoodle cookie! Cinnamon sugar goodness in creamy oat milk.\n\nServe warm or cold. Dust with extra cinnamon.", nutrition: { calories: 70, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 14, fiber_g: 1, sugars_g: 5, protein_g: 2, calcium_mg: 10, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 55 } },
    { id: "dessert013", name: "Maple Walnut Cashew Cream", ingredients: ["1/2 cup Cashews", "1/2 cup Walnuts"], flavorings: ["2 tbsp Maple Syrup", "1/2 tsp Vanilla"], description: "Rich walnuts and creamy cashews with strong maple flavor. Decadent.\n\nGreat base for ice cream or enjoying as a rich drink.", nutrition: { calories: 125, fat_g: 10.5, saturated_fat_g: 1.1, carbs_g: 7.5, fiber_g: 1, sugars_g: 5.5, protein_g: 3, calcium_mg: 20, vitamin_d_iu: 0, iron_mg: 0.7, potassium_mg: 95 } },
    { id: "unique006", name: "Savory Mushroom Almond Milk", ingredients: ["1 cup Raw Almonds"], flavorings: ["1/4 cup Dried Mushrooms (like shiitake, rehydrated slightly)", "1/2 tsp Nutritional Yeast", "Pinch Garlic Powder", "Pinch Thyme"], description: "An earthy, umami-rich savory milk. Unexpected but great for certain dishes.\n\nUse as a base for creamy mushroom soups or savory gravies.", nutrition: { calories: 55, fat_g: 5, saturated_fat_g: 0.4, carbs_g: 2.5, fiber_g: 1.5, sugars_g: 0.5, protein_g: 2.5, calcium_mg: 65, vitamin_d_iu: 0, iron_mg: 0.5, potassium_mg: 80 } }, // Mushrooms add minerals
    { id: "unique007", name: "Hibiscus Berry Oat Infusion", ingredients: ["1 cup Rolled Oats"], flavorings: ["1 tbsp Dried Hibiscus Flowers (steeped)", "1/4 cup Mixed Berries", "1 tbsp Honey"], description: "Tart hibiscus and sweet berries create a vibrant pink, tangy milk.\n\nBeautiful color, refreshing taste. Serve chilled.", nutrition: { calories: 70, fat_g: 1, saturated_fat_g: 0.2, carbs_g: 14.5, fiber_g: 1.5, sugars_g: 6.5, protein_g: 2, calcium_mg: 15, vitamin_d_iu: 0, iron_mg: 0.6, potassium_mg: 75 } }, // Hibiscus adds Vit C
    // ... Continue adding recipes...
    { id: "final004", name: "Last Recipe Example", ingredients: ["1 cup Placeholder Nuts"], flavorings: ["Flavor"], description: "This is the last recipe in the list.\n\nNo comma follows its closing brace.", nutrition: { calories: 100, fat_g: 5, saturated_fat_g: 0.5, carbs_g: 10, fiber_g: 1, sugars_g: 5, protein_g: 3, calcium_mg: 50, vitamin_d_iu: 0, iron_mg: 1, potassium_mg: 100 } }
    // NO COMMA after the last recipe's closing brace
]; // End of the recipes array
